# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gravity
email: hemangsk@gmail.com
description: The Liberal Jekyll Theme
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kariemoorman.com" # the base hostname & protocol for your site
github_username:  kariemoorman
paginate: 5
theme-dark: true #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown

